import * as React from "react"

const Spinner = (props: React.SVGProps<SVGSVGElement>) => {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width={70}
            height={70}
            preserveAspectRatio="xMidYMid"
            style={{
                shapeRendering: "auto",
                display: "block",
                background: "#fff",
            }}
            viewBox="0 0 100 100"
            {...props}
        >
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
            >
                <animate
                    attributeName="opacity"
                    begin="-0.9166666666666666s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(30 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.8333333333333334s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(60 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.75s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(90 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.6666666666666666s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(120 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.5833333333333334s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(150 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.5s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(180 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.4166666666666667s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(210 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.3333333333333333s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(240 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.25s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(270 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.16666666666666666s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(300 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.08333333333333333s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
            <rect
                width={7}
                height={15}
                x={46.5}
                y={22.5}
                fill="#0099e5"
                rx={3.5}
                ry={5.55}
                transform="rotate(330 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="0s"
                    dur="1s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                />
            </rect>
        </svg>
    )
}
export default Spinner;
